opengl_prism: opengl_prism.c ../2D/*.c ../*.c
	gcc opengl_prism.c ../2D/*.c  ../3D/*.c ../*.c -lm -lglfw -lGL -o build/opengl_prism 

opengl_triangle: opengl_triangle.c ../2D/*.c ../*.c
	gcc opengl_triangle.c ../2D/*.c  ../3D/*.c ../*.c -lm -lglfw -lGL -o build/ogl_triangle 
